export const equipements = [
    {
        "id": 1,
        "nom": "Dell Latitude 5520",
        "categorie": "Ordinateurs",
        "marque": "Dell",
        "modele": "Latitude 5520",
        "numero_serie": "DL55201234",
        "date_acquisition": "2023-06-15",
        "prix": 1299.99,
        "etat": "Bon",
        "utilisateur": "Jean Dupont",
        "localisation": "Bureau 101",
        "derniere_maintenance": "2024-01-10",
        "notes": "Ordinateur portable professionnel"
    },
    {
        "id": 2,
        "nom": "HP LaserJet Pro M404dn",
        "categorie": "Imprimantes",
        "marque": "HP",
        "modele": "LaserJet Pro M404dn",
        "numero_serie": "HPLJ4041234",
        "date_acquisition": "2023-08-20",
        "prix": 349.99,
        "etat": "Excellent",
        "utilisateur": "Service Marketing",
        "localisation": "Salle d'impression",
        "derniere_maintenance": "2024-02-05",
        "notes": "Imprimante réseau départementale"
    },
    {
        "id": 3,
        "nom": "Dell PowerEdge R740",
        "categorie": "Serveurs",
        "marque": "Dell",
        "modele": "PowerEdge R740",
        "numero_serie": "DLPE7401234",
        "date_acquisition": "2023-04-10",
        "prix": 5999.99,
        "etat": "Excellent",
        "utilisateur": "Service IT",
        "localisation": "Salle serveur",
        "derniere_maintenance": "2024-01-20",
        "notes": "Serveur principal applications"
    },
    {
        "id": 4,
        "nom": "Logitech MX Master 3",
        "categorie": "Périphériques",
        "marque": "Logitech",
        "modele": "MX Master 3",
        "numero_serie": "LGT789012",
        "date_acquisition": "2023-09-15",
        "prix": 99.99,
        "etat": "Neuf",
        "utilisateur": "Sophie Lambert",
        "localisation": "Bureau 203",
        "derniere_maintenance": null,
        "notes": "Souris ergonomique haute précision"
    },
    {
        "id": 5,
        "nom": "iPhone 13 Pro",
        "categorie": "Téléphones",
        "marque": "Apple",
        "modele": "iPhone 13 Pro",
        "numero_serie": "IPH567890",
        "date_acquisition": "2023-10-01",
        "prix": 1099.99,
        "etat": "Excellent",
        "utilisateur": "Marie Dubois",
        "localisation": "Mobile",
        "derniere_maintenance": "2024-02-15",
        "notes": "Téléphone professionnel - Directrice IT"
    },
    {
        "id": 6,
        "nom": "Adobe Creative Cloud",
        "categorie": "Logiciels",
        "marque": "Adobe",
        "modele": "Creative Cloud 2024",
        "numero_serie": "ADO123456",
        "date_acquisition": "2024-01-01",
        "prix": 599.99,
        "etat": "Actif",
        "utilisateur": "Équipe Design",
        "localisation": "Licence réseau",
        "derniere_maintenance": "2024-03-01",
        "notes": "Suite créative complète - 5 licences"
    },
    {
        "id": 7,
        "nom": "Cisco Catalyst 9300",
        "categorie": "Réseau",
        "marque": "Cisco",
        "modele": "Catalyst 9300",
        "numero_serie": "CSC098765",
        "date_acquisition": "2023-07-15",
        "prix": 3999.99,
        "etat": "Excellent",
        "utilisateur": "Service IT",
        "localisation": "Salle réseau principale",
        "derniere_maintenance": "2024-02-28",
        "notes": "Switch principal - 48 ports"
    }
];
